---
# tasks file for VM_delete
- name: Gather volume info from storage
  ibm.spectrum_virtualize.ibm_svc_info:
    clustername: "{{ svc_cluster_name }}"
    username: "{{ svc_user_name }}"
    password: "{{ svc_user_passwd }}"
    log_path: /tmp/playbook.debug
    name: gather_info
    state: info
    gather_subset: host
  register: svc_info_host

- name: Output information in verbosity mode
  debug:
    msg: "{{ svc_info_host }}"
    verbosity: 1

- name: Set OS Distro search for ALL parameters
  set_fact:
    host_query: "Host[*].{name: name, status: status}"

- name: Filter image list
  set_fact:
    host_info: "{{ svc_info_host | json_query(host_query) }}"

- name: Show host information
  debug:
    msg: "{{ host_info }}"
