---
- name: Prepare flashcopy mapping on SVC Volume
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    - svc_cluster_name: IBM-FS9100
    - svc_user_name: jwilcock

  vars_prompt:
    - name: "svc_user_passwd"
      prompt: "Enter password for {{ svc_user_name }} on SVC {{svc_cluster_name}}"
      private: yes
      confirm: no
    - name: "svc_src_vol"
      prompt: "Enter name of source volume of flashcopy mapping to prepare"
      private: yes
      confirm: no

  tasks:
    - name: prepare flashcopy mapping
      import_role:
        name: prep_svc_fcmap
