---
- name: Gather volume info from storage
  ibm.spectrum_virtualize.ibm_svc_info:
    clustername: "{{ svc_cluster_name }}"
    username: "{{ svc_user_name }}"
    password: "{{ svc_user_passwd }}"
    log_path: /tmp/playbook.debug
    name: gather_info
    state: info
    gather_subset: host
  register: svc_info_host

- name: Output information in verbosity mode
  debug:
    msg: "{{ svc_info_host }}"
    verbosity: 1

- name: Show host information
  set_fact:
    host_query: "Host[*].{name: name, status: status}"

- name: Filter image list
  set_fact:
    host_info: "{{ svc_info_host | json_query(host_query) }}"

- name: Show host information
  debug:
    msg: "{{ host_info }}"

- name: Output host list
  set_fact:
    VM_debug: "Seq: {{ Host_Seq }}, Name: {{ item.name }}, Status: {{ item.status }}"
  with_items: "{{Host_Heading}},{{ host_info }}"
  loop_control:
    index_var: Host_Seq
    label: "{% if Host_Seq == 0 %}Seq{% else %}{{ Host_Seq|center(width=3) }}{% endif %} | {{ item.name|center(width=35) }}|{{ item.status|center(width=15) }} "
  register: Host_Array

- name: Debug - Output Host List
  debug:
    var: Host_Array.results
    verbosity: 1
