---
- name: Gather volume info from storage
  ibm.spectrum_virtualize.ibm_svc_info:
    clustername: "{{ svc_cluster_name }}"
    username: "{{ svc_user_name }}"
    password: "{{ svc_user_passwd }}"
    log_path: /tmp/playbook.debug
    name: gather_info
    state: info
    gather_subset: vol
  register: svc_info_vol

- name: Output information in verbosity mode
  debug:
    msg: "{{ svc_info_vol }}"
  verbosity: 0

- name: Set volume information
  set_fact:
    volume_query: "Volume[*].{name: name, status: status, capacity: capacity}"

- name: Filter volume list
  set_fact:
    volume_info: "{{ svc_info_vol | json_query(volume_query) }}"

- name: Show volume information
  debug:
    msg: "{{ volume_info }}"
