---
- name: Add volume to IBM Spectrum Virtualize
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    svc_cluster_name: IBM-FS9100
    svc_user_name: scunliffe
  #  svc_new_vol_name: test-vol1
  #  svc_new_vol_size: '10'

  vars_prompt:
    - name: "svc_user_passwd"
      prompt: "Enter password for {{ svc_user_name }} on SVC {{ svc_cluster_name }}"
      private: yes
      confirm: no

  tasks:
    - name: Gather volume info from storage
      ibm_svc_vdisk:
        clustername: "{{ svc_cluster_name }}"
        username: "{{ svc_user_name }}"
        password: "{{ svc_user_passwd }}"
        log_path: /tmp/playbook.debug
        state: present
        name: "{{ svc_new_vol_name }}"
        size: "{{ svc_new_vol_size }}"
        mdiskgrp: Primary_Pool
        unit: gb
        rsize: '20%'
        autoexpand: true
      register: svc_new_vol_create

    - name: Output information in verbosity mode
      debug:
        msg: "{{ svc_new_vol_create }}"
        verbosity: 0

#    - name: Set volume information
#     set_fact:
#        volume_query: "Volume[*].{name: name, status: status, capacity: capacity}"

#    - name: Filter volume list      set_fact:
#        volume_info: "{{ svc_info_vol | json_query(volume_query) }}"

#    - name: Show volume information
#      debug:
#        msg: "{{ volume_info }}"
