---
- name: Add volume to IBM Spectrum Virtualize
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    svc_cluster_name: IBM-FS9100
    svc_user_name: scunliffe
  #  svc_new_vol_name: test-vol1
  #  svc_new_vol_size: '10'

  vars_prompt:
    - name: "svc_user_passwd"
      prompt: "Enter password for {{ svc_user_name }} on SVC {{ svc_cluster_name }}"
      private: yes
      confirm: no

  tasks:
    - name: Create new vdisk
      import_role:
        name: add_svc_volume
