---
- name: Show the volume information from the IBM Spectrum Virtualize
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    svc_cluster_name: IBM-FS9100
    svc_user_name: scunliffe

  vars_prompt:
    - name: "svc_user_passwd"
      prompt: "Enter password for {{ svc_user_name }} on SVC {{ svc_cluster_name }}"
      private: yes
      confirm: no

  tasks:
    - name: Gather Volume information
      import_role:
        name: list_svc_volumes
