---
- name: Show the client VM information
  gather_facts: yes
  hosts: all
  vars:
#    svc_cluster_name: IBM-FS9100
#    svc_user_name: scunliffe

#  vars_prompt:
#    - name: "svc_user_passwd"
#      prompt: "Enter password for {{ svc_user_name }} on SVC {{ svc_cluster_name }}"
#      private: yes
#      confirm: no

  tasks:
    - name: Show client volumes
      import_role:
        name: show_client_volumes_os
