---
- name: Show the host information from the IBM Spectrum Virtualize
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    svc_cluster_name: IBM-FS9100
    svc_user_name: scunliffe

  vars_prompt:
    - name: "svc_user_passwd"
      prompt: "Enter password for {{ svc_user_name }} on SVC {{ svc_cluster_name }}"
      private: yes
      confirm: no

  tasks:
    - name: Gather volume info from storage
      ibm_svc_info:
        clustername: "{{ svc_cluster_name }}"
        username: "{{ svc_user_name }}"
        password: "{{ svc_user_passwd }}"
        log_path: /tmp/playbook.debug
        name: gather_info
        state: info
        gather_subset: host
      register: svc_info_host

    - name: Output information in verbosity mode
      debug:
        msg: "{{ svc_info_host }}"
        verbosity: 1

    - name: Set OS Distro search for ALL parameters
      set_fact:
        host_query: "Host[*].{name: name, status: status}"

    - name: Filter image list
      set_fact:
        host_info: "{{ svc_info_host | json_query(host_query) }}"

    - name: Show host information
      debug:
        msg: "{{ host_info }}"
